
auth:
  environment: development
  providers:
    oauth2Proxy: {}
    
signInPage: oauth2Proxy

catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        realm: ${KEYCLOAK_REALM}
        loginRealm: ${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        userQuerySize: 250
        groupQuerySize: 250
        schedule: # optional; same options as in TaskScheduleDefinition
           # supports cron, ISO duration, "human duration" as used in code
           frequency: { minutes: 1 }
           # supports ISO duration, "human duration" as used in code
           timeout: { minutes: 1 }
           initialDelay: { seconds: 15 }
  rules:
     - allow: [Component, Group, User, Resource, Location, Template]
    
integrations:
  bitbucketCloud:
    - username: ${BITBUCKET_CLOUD_USERNAME}
      appPassword: ${BITBUCKET_CLOUD_PASSWORD}      

enabled:
  keycloak: true 